require "byebug"
require "colorize"

load "./ds/stack.rb"
load "./ds/multi_stack.rb"
load "./ds/hash_map.rb"
load "./ds/linked_list.rb"
load "./ds/array_list.rb"
load "./ds/queue.rb"
load "./ds/squeue.rb"
load "./ds/buffet_stack.rb"
load "./ds/b_s_tree.rb"
load "./ds/min_heap.rb"
load "./ds/trie.rb"
load "./ds/graph.rb"
